routes/todo_routes.py
from flask import Blueprint

def create_todo_routes(todo_controller):
    todo_routes = Blueprint('todo_routes', __name__)

    @todo_routes.route('/home')
    def home():
        return todo_controller.home()

    @todo_routes.route('/createListing.html', methods=['POST', 'GET'])
    def create_listing():
        return todo_controller.create_listing()

    @todo_routes.route('/complete_todo/<todo_id>', methods=['POST'])
    def complete_todo(todo_id):
        return todo_controller.complete_todo(todo_id)

    @todo_routes.route('/view_history')
    def view_history():
        return todo_controller.view_history()

    @todo_routes.route('/delete_todo/<todo_id>', methods=['POST'])
    def delete_todo(todo_id):
        return todo_controller.delete_todo(todo_id)

    @todo_routes.route('/edit_todo/<todo_id>', methods=['GET'])
    def edit_todo_form(todo_id):
        return todo_controller.edit_todo_form(todo_id)

    @todo_routes.route('/update_todo/<todo_id>', methods=['POST'])
    def update_todo(todo_id):
        return todo_controller.update_todo(todo_id)

    @todo_routes.route('/delete_completed_todo/<todo_id>', methods=['POST'])
    def delete_completed_todo(todo_id):
        return todo_controller.delete_completed_todo(todo_id)

    return todo_routes

routes/user_routes.py
from flask import Blueprint

def create_user_routes(user_controller):
    user_routes = Blueprint('user_routes', __name__)

    @user_routes.route("/")
    def render_login():
        return user_controller.render_login()

    @user_routes.route('/login', methods=['POST', 'GET'])
    def login():
        return user_controller.login()

    @user_routes.route('/signup', methods=['POST', 'GET'])
    def signup():
        return user_controller.signup()

    @user_routes.route('/logout')
    def logout():
        return user_controller.logout()

    return user_routes

templates/createListing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Listing</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="creatlisting-body">
    <div class="create_listing-card">
      <h2>Create Listing</h2>
      <form action="{{ url_for('todo_routes.create_listing') }}" method="post">
        <div class="mb-3">
          <label class="form-label" for="title">Title:</label>
          <input
            class="form-control"
            type="text"
            id="title"
            name="title"
            required
          />
        </div>
        <div class="mb-3">
          <label class="form-label" for="description">Description:</label>
          <textarea
            class="form-control"
            id="description"
            name="description"
            required
          ></textarea>
        </div>
        <div class="mb-3">
          <label class="form-label" for="deadline">Deadline:</label>
          <input
            class="form-control"
            type="date"
            id="deadline"
            name="deadline"
            required
          />
        </div>
        <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </body>
</html>

templates/edit_todo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edit Todo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="edit-todo-body">
    <div class="main-content p-2" style="margin: 0 auto; margin-top: 2rem">
      <h2>Edit Todo</h2>
      <form
        action="{{ url_for('todo_routes.update_todo', todo_id=todo['_id']) }}"
        method="post"
      >
        <div class="mb-3">
          <label class="form-label" for="title">Title:</label>
          <input
            class="form-control"
            type="text"
            id="title"
            name="title"
            value="{{ todo['title'] }}"
            required
          />
        </div>
        <div class="mb-3">
          <label class="form-label" for="description">Description:</label>
          <textarea
            class="form-control"
            id="description"
            name="description"
            required
          >
{{ todo['description'] }}</textarea
          >
        </div>
        <div class="mb-3">
          <label class="form-label" for="deadline">Deadline:</label>
          <input
            class="form-control"
            type="date"
            id="deadline"
            name="deadline"
            value="{{ todo['deadline'] }}"
            required
          />
        </div>
        <button class="btn btn-primary" type="submit">Update</button>
      </form>
    </div>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="home">
    <div id="my-container">
      <!-- Sidebar Section -->
      <div class="sidebar p-2">
        <div class="profile-card">
          <img
            src="{{ url_for('static', filename='assets/profile.png') }}"
            alt="Profile Picture"
            class="profile-pic"
          />
          <h6>{{ username }}</h6>
          <div class="logout m-4">
            <form action="{{ url_for('user_routes.logout') }}" method="get">
              <button
                class="btn btn-outline-dark form-control my-2"
                type="submit"
              >
                Logout
              </button>
            </form>
          </div>
        </div>
        <div class="sub-title">
          <h4>Todo:</h4>
        </div>
        <div class="show-todo">
          <button class="btn btn-outline-dark form-control my-2">
            Show Todo
          </button>
        </div>
        <div class="create-todo">
          <form action="{{ url_for('todo_routes.create_listing') }}" method="get">
            <button class="btn btn-outline-dark form-control my-2 create-todo">
              Create Todo
            </button>
          </form>
        </div>
        <div class="sub-title">
          <h4 style="display: inline">Completed</h4>
          <h1 style="display: inline">&#10004;</h1>
        </div>
        <div class="todo-history">
          <form action="{{ url_for('todo_routes.view_history') }}" method="get">
            <button class="btn btn-outline-dark form-control my-2">
              View History
            </button>
          </form>
        </div>
      </div>

      <!-- Main Content Section -->
      <div class="main-content p-2">
        <!-- Toggle Buttons for Date Filters -->
        <div
          class="btn-group m-1"
          role="group"
          aria-label="Basic radio toggle button group"
        >
          <input
            type="radio"
            class="btn-check"
            name="btnradio"
            id="btnradio1"
            autocomplete="off"
            checked
          />
          <label class="btn btn-outline-dark" for="btnradio1">Today</label>

          <input
            type="radio"
            class="btn-check"
            name="btnradio"
            id="btnradio2"
            autocomplete="off"
          />
          <label class="btn btn-outline-dark" for="btnradio2">This Week</label>

          <input
            type="radio"
            class="btn-check"
            name="btnradio"
            id="btnradio3"
            autocomplete="off"
          />
          <label class="btn btn-outline-dark" for="btnradio3">This Month</label>
        </div>

        <!-- Display Area for Todo Items -->
        <div class="btns-result m-1">
          <div class="display-today">
            <!-- Today Task Cards -->
            {% for todo in todos_today %}
            <div class="todo-card">
              <input
                type="checkbox"
                onchange="completeTodo('{{ todo._id }}')"
              />
              <h4 class="title">{{ todo.title }}</h4>
              <p class="description">{{ todo.description }}</p>
              <strong class="deadline">{{ todo.deadline }}</strong>
              <div id="btn-group">
                <form
                  action="{{ url_for('todo_routes.edit_todo_form', todo_id=todo['_id']) }}"
                  method="get"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-dark mx-2">Edit</button>
                </form>
                <form
                  action="{{ url_for('todo_routes.delete_todo', todo_id=todo['_id']) }}"
                  method="POST"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>

          <div class="display-week display-none">
            <!-- This Week Task Cards -->
            {% for todo in todos_this_week %}
            <div class="todo-card">
              <input
                type="checkbox"
                onchange="completeTodo('{{ todo._id }}')"
              />
              <h4 class="title">{{ todo.title }}</h4>
              <p class="description">{{ todo.description }}</p>
              <strong class="deadline">{{ todo.deadline }}</strong>
              <div id="btn-group">
                <form
                  action="{{ url_for('todo_routes.edit_todo_form', todo_id=todo['_id']) }}"
                  method="get"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-dark mx-2">Edit</button>
                </form>
                <form
                  action="{{ url_for('todo_routes.delete_todo', todo_id=todo['_id']) }}"
                  method="POST"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>

          <div class="display-month display-none">
            <!-- This Month Task Cards -->
            {% for todo in todos_this_month %}
            <div class="todo-card">
              <input
                type="checkbox"
                onchange="completeTodo('{{ todo._id }}')"
              />
              <h4 class="title">{{ todo.title }}</h4>
              <p class="description">{{ todo.description }}</p>
              <strong class="deadline">{{ todo.deadline }}</strong>
              <div id="btn-group">
                <form
                  action="{{ url_for('todo_routes.edit_todo_form', todo_id=todo['_id']) }}"
                  method="get"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-dark mx-2">Edit</button>
                </form>
                <form
                  action="{{ url_for('todo_routes.delete_todo', todo_id=todo['_id']) }}"
                  method="POST"
                  style="display: inline"
                >
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="static/style.css" />
  </head>
  <body id="login-container">
    <div class="card">
      <form action="/login" method="post">
        <div class="username m-2">
          <label class="form-label" for="username">Username:</label>
          <input type="text" class="username form-control" name="username" />
        </div>
        <div class="password m-2">
          <label class="form-label" for="password">password:</label>
          <input
            type="password"
            class="password form-control"
            name="password"
          />
        </div>
        <div class="m-2">
          <button type="submit" class="login btn btn-outline-success">
            Login
          </button>
          <a href="{{ url_for('user_routes.signup') }}" class="login btn btn-outline-dark">
            Signup
          </a>
        </div>
      </form>
    </div>
  </body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SignUp</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="static/style.css" />
  </head>
  <body id="login-container">
    <div class="card">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %} {% endif %} {% endwith %}
      <form action="{{ url_for('user_routes.signup') }}" method="post">
        <div class="username m-2">
          <label class="form-label" for="username">Username:</label>
          <input type="text" class="username form-control" name="username" />
        </div>
        <div class="email m-2">
          <label class="form-label" for="email">email:</label>
          <input type="email" class="email form-control" name="email" />
        </div>
        <div class="password m-2">
          <label class="form-label" for="password">password:</label>
          <input
            type="password"
            class="password form-control"
            name="password"
          />
        </div>
        <div class="m-2">
          <button type="submit" class="login btn btn-outline-dark">
            Signup
          </button>
        </div>
      </form>
    </div>
  </body>
</html>

templates/view_history.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Completed Todos</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="complete_todo_body">
    <div class="main-content p-2" style="margin: 0 auto; margin-top: 2rem">
      <div class="completed-todo-title-container">
        <h2 class="complete_todo_title">Completed Todos</h2>
        <a href="{{ url_for('todo_routes.home') }}" class="btn btn-outline-dark"
          >Back to Home</a
        >
      </div>

      <div class="btns-result m-1">
        {% for todo in completed_todos %}
        <div class="todo-card">
          <h4 class="title">{{ todo.title }}</h4>
          <p class="description">{{ todo.description }}</p>
          <strong class="deadline">{{ todo.deadline }}</strong>
        </div>
        <div id="btn-group">
          <form
            action="{{ url_for('todo_routes.delete_completed_todo', todo_id=todo['_id']) }}"
            method="POST"
            style="display: inline"
          >
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
</html>